### ISSUE TITLE
sort price not working along with previewing price

### ISSUE THREAD

**Issue by Dragongas2003** [AndreyMrovol/LethalTerminalFormatter#6] opened 2024-02-27 19:17 UTC
this seems to be a new issue was working fine then mods were updated and it has since stopped working correctly 
![image](https://github.com/AndreyMrovol/LethalTerminalFormatter/assets/153855526/35cd92d2-f015-45d9-93b5-ba14fa2e5444)

![image](https://github.com/AndreyMrovol/LethalTerminalFormatter/assets/153855526/63fd09d7-4669-4f71-8726-7a37862129d7)

Heres the log

[LogOutput.log](https://github.com/AndreyMrovol/LethalTerminalFormatter/files/14424649/LogOutput.log)

**Comment by Dragongas2003** [comment] 2024-02-27 21:20
found a temporary fix for now. if you are using advanced company all that is needed to be done to fix it is to checkmark all the prices of the moons. 

![image](https://github.com/AndreyMrovol/LethalTerminalFormatter/assets/153855526/2dd428b9-6f00-451e-987d-30bff4f72310)

this fix worked for me so if anyone else encounters the issue hope this helps

**Comment by AndreyMrovol** [comment] 2024-02-27 23:03
What's the AC version?

**Comment by AndreyMrovol** [comment] 2024-02-27 23:08
Ok, i've checked in your log - it's `1.1.10`

Sadly, I'm not planning to support any AC version above 1.1.2, moreover this issue might be caused by LLL / AC's implementation of LLL / anything else - it's not a display problem, which is a scope of my mod.

**Closed by AndreyMrovol** 2024-02-27 23:08 UTC
